<div class="address-block">
    <div class="footer-contact-phone">
        <div class="footer-contact-phone-image">☎Telephone: +961 (0)1 513599</div>
        <div class="footer-contact-mail"><a href = "mailto: info@borninteractive.com">Email Us</a></div>
    </div>
    <div class="footer-contact-address">
        <a target="_blank" href="https://www.google.com/maps/place/Born+Interactive/@33.8787954,35.5330683,17z/data=!3m1!4b1!4m5!3m4!1s0x151f17032c3e1245:0xdf045a8a7f6265e5!8m2!3d33.878791!4d35.535257">
        check our location on map
        </a>
        <br>
        210 Center, 1st Floor, Jisr el Wati Street, <br/>
        Horsh Tabet, Sin El Fil
    </div>
</div>